#!/bin/bash
depfile=$(mktemp)
gcc -MM *.c | sed -e 's/\\$/@@@/' -e 's/$/###/' | tr '\n' ' ' | sed -e 's/@@@### *//g' | sed -e 's/### /\n/g' > $depfile
declare -A impliedobj
while read line; do
    objfile=$(echo $line|awk -F: '{print $1}')
    addfile=$(echo $line|awk -F: '{print $2}')
    implied=""
    for f in $addfile; do
        if [[ "${f%.c}.o" != "$objfile" ]]; then
            if [[ "${f%.h}.o" != "$objfile" ]]; then
                addobjfile=${f%.h}.c
                if [[ -f $addobjfile ]]; then 
                    addobjfile=${f%.h}.o
                    implied="${implied} $addobjfile"
                fi
            fi
        fi
    done
    impliedobj[$objfile]=$implied
    #echo "$objfile -> ${impliedobj[$objfile]}"
done < $depfile
mainfiles=$(grep -l main\( *.c)
exenames=""
for mainfile in $mainfiles; do
    exename=${mainfile%.c}
    exenames="$exenames $exename"
done
echo "# makefile generated by buildconfig.sh for: "
echo "#$exenames"
echo -n '# on '
date
echo -n '# by '
whoami
echo
echo -e "all: $exenames"
echo
cat $depfile
echo
for mainfile in $mainfiles; do
    exename=${mainfile%.c}
    newobjects="${mainfile%.c}.o"
    objects=""
    while [[ "$newobjects" != "$objects" ]]; do
        objects=$newobjects
        newobjects=""
        for o in $objects; do
            newobjects="$newobjects $o ${impliedobj[$o]}"
        done
        newobjects=$(echo $newobjects| tr ' ' '\n' |sort|uniq|tr '\n' ' ')
    done
    allobj="$allobj $newobjects"
    echo "$exename: $newobjects"
    echo -e '\t${CC} ${LDFLAGS} -o $@ $^ ${LDLIBS}\n'
done
newallobj="$allobj $newobjects"
allobj=""
while [[ "$newallobj" != "$allobj" ]]; do
    allobj=$newallobj
    newallobj=""
    for o in $allobj; do
        newallobj="$newallobj $o ${impliedobj[$o]}"
    done
    newallobj=$(echo $newallobj| tr ' ' '\n' |sort|uniq|tr '\n' ' ')
done
echo -e "\nclean:\n\trm -f ${newallobj}"